### ISSUE TITLE
Does not build with on systems using openssl 1.1

### ISSUE THREAD

**Issue by rotty** [JanLikar/cargo-clone#10]
This probably due to refererring to an cargo version (0.9) that transitively depends on non a libssh2 version not yet compatible with OpenSSL 1.1. The following happens upon `cargo install cargo-clone` on Debian stretch amd64 system with `rustc 1.14.0-beta.2 (e627a2e6e 2016-11-16)`:

> Build failed, waiting for other jobs to finish...
> error: failed to compile `cargo-clone v0.1.0`, intermediate artifacts can be found at `/tmp/user/1000/cargo-install.avhrR20HO7OI`

> Caused by:
>   failed to run custom build command for `libssh2-sys v0.1.41`
> process didn't exit successfully: `/tmp/user/1000/cargo-install.avhrR20HO7OI/release/build/libssh2-sys-5ede2d7f8ada4bc1/build-script-build` (exit code: 101)
> --- stdout
> running: "cmake" "/home/rotty/.cargo/registry/src/github.com-1ecc6299db9ec823/libssh2-sys-0.1.41/libssh2" "-DCRYPTO_BACKEND=OpenSSL" "-DBUILD_SHARED_LIBS=OFF" "-DENABLE_ZLIB_COMPRESSION=ON" "-DCMAKE_INSTALL_LIBDIR=lib" "-DBUILD_EXAMPLES=OFF" "-DBUILD_TESTING=OFF" "-DCMAKE_INSTALL_PREFIX=/tmp/user/1000/cargo-install.avhrR20HO7OI/release/build/libssh2-sys-5ede2d7f8ada4bc1/out" "-DCMAKE_C_FLAGS= -O0 -ffunction-sections -fdata-sections -m64 -fPIC" "-DCMAKE_C_FLAGS_RELEASE= -O0 -ffunction-sections -fdata-sections -m64 -fPIC" "-DCMAKE_C_COMPILER=/home/rotty/bin/cc" "-DCMAKE_CXX_FLAGS= -O0 -ffunction-sections -fdata-sections -m64 -fPIC" "-DCMAKE_CXX_FLAGS_RELEASE= -O0 -ffunction-sections -fdata-sections -m64 -fPIC" "-DCMAKE_CXX_COMPILER=/home/rotty/bin/c++" "-DCMAKE_BUILD_TYPE=Release"
> [...]
> /home/rotty/.cargo/registry/src/github.com-1ecc6299db9ec823/libssh2-sys-0.1.41/libssh2/src/openssl.c: In function ‘_libssh2_rsa_new’:
> /home/rotty/.cargo/registry/src/github.com-1ecc6299db9ec823/libssh2-sys-0.1.41/libssh2/src/openssl.c:71:11: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
>      (*rsa)->e = BN_new();
>            ^~
> /home/rotty/.cargo/registry/src/github.com-1ecc6299db9ec823/libssh2-sys-0.1.41/libssh2/src/openssl.c: In function ‘_libssh2_dsa_new’:
> /home/rotty/.cargo/registry/src/github.com-1ecc6299db9ec823/libssh2-sys-0.1.41/libssh2/src/openssl.c:130:14: error: dereferencing pointer to incomplete type ‘DSA {aka struct dsa_st}’
>      (*dsactx)->p = BN_new();
>               ^~
> /home/rotty/.cargo/registry/src/github.com-1ecc6299db9ec823/libssh2-sys-0.1.41/libssh2/src/openssl.c: In function ‘_libssh2_dsa_sha1_verify’:
> /home/rotty/.cargo/registry/src/github.com-1ecc6299db9ec823/libssh2-sys-0.1.41/libssh2/src/openssl.c:156:13: error: storage size of ‘dsasig’ isn’t known
>      DSA_SIG dsasig;
>              ^~~~~~
> /home/rotty/.cargo/registry/src/github.com-1ecc6299db9ec823/libssh2-sys-0.1.41/libssh2/src/openssl.c:156:13: warning: unused variable ‘dsasig’ [-Wunused-variable]
> In file included from /usr/include/openssl/asn1.h:24:0,
>                  from /usr/include/openssl/rsa.h:16,
>                  from /home/rotty/.cargo/registry/src/github.com-1ecc6299db9ec823/libssh2-sys-0.1.41/libssh2/src/openssl.h:42,
>                  from /home/rotty/.cargo/registry/src/github.com-1ecc6299db9ec823/libssh2-sys-0.1.41/libssh2/src/crypto.h:42,
>                  from /home/rotty/.cargo/registry/src/github.com-1ecc6299db9ec823/libssh2-sys-0.1.41/libssh2/src/libssh2_priv.h:140,
>                  from /home/rotty/.cargo/registry/src/github.com-1ecc6299db9ec823/libssh2-sys-0.1.41/libssh2/src/openssl.c:41:
> /home/rotty/.cargo/registry/src/github.com-1ecc6299db9ec823/libssh2-sys-0.1.41/libssh2/src/openssl.c: In function ‘_libssh2_dsa_sha1_sign’:
> /home/rotty/.cargo/registry/src/github.com-1ecc6299db9ec823/libssh2-sys-0.1.41/libssh2/src/openssl.c:597:29: error: dereferencing pointer to incomplete type ‘DSA_SIG {aka struct DSA_SIG_st}’
>      r_len = BN_num_bytes(sig->r);
>                              ^
> make[2]: *** [src/CMakeFiles/libssh2.dir/openssl.c.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[1]: *** [src/CMakeFiles/libssh2.dir/all] Error 2
> make: *** [all] Error 2
> thread 'main' panicked at '
> command did not execute successfully, got: exit code: 2
> 
> build script failed, must exit now', /home/rotty/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.19/src/lib.rs:542
> note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by JanLikar** [comment]
I have published a new version of this crate that features the latest stable version of Cargo. Could you try installing cargo-clone again, to see if the problem persists?

**Comment by dralley** [comment]
This works fine for me @JanLikar - Fedora 29 w/ openssl 1.1

**Comment by rotty** [comment]
Sorry for not noticing the heads-up for over 2 years ;-). I've just checked installing `cargo-clone` 0.1.3 on my machine, now running Debian Buster, and it worked nicely.
