### ISSUE TITLE
cargo clone result in a full git repo

### ISSUE THREAD

**Issue by hoangtranwork** [JanLikar/cargo-clone#16]
Hi, I notice that `cargo clone` only download the source code of the crate, instead of the full git repo. Is there an option to get the git repo too?, so the result will be similar to a `git clone` run.

**Comment by pravic** [comment]
Yeah, it would allow to download submodules too. Currently it downloads a source tree with .gitmodules file, but it is useless without .git repository.

**Comment by joshtriplett** [comment]
I'm interested in this as well. I tried cargo clone, expecting to get a repository with which I could contribute to a crate, but just ended up with the source code sans repository instead.

**Comment by JanLikar** [comment]
According to http://doc.crates.io/crates-io.html, files ignored by vcs are not published by default, hence they cannot be cloned from crates.io.

A possible workaround is to use git to checkout the repo directly if its url is set in `Cargo.toml`.

**Comment by joshtriplett** [comment]
@JanLikar That's exactly what I was expecting: just get the repository URL from the Cargo metadata (which doesn't even require downloading the crate) and feed it to `git clone`.

**Comment by pravic** [comment]
Yeah, possible via an additional option to clone the git repository.

**Comment by joshtriplett** [comment]
@JanLikar I'm unlikely to be able to work on this any time soon, so if someone else wants to do so, please feel free.

**Comment by matthiaskrgr** [comment]
I was also looking for an easy way to `git clone` the repo of a crate that was set on crates.io.

It seems that [cargo-clone-crate](https://crates.io/crates/cargo-clone-crate) by @ehuss provides this functionality. :)
