### ISSUE TITLE
Cloning Specific Version from Crates.io

### ISSUE THREAD

**Issue by iwillspeak** [JanLikar/cargo-clone#17]
I'm trying to clone a specific version of a crate from Crates.io using this command. The crate version is 64.0.0. If i run `cargo clone --vers 64.0.0 onig_sys` I get version 64.0.1 rather than 64.0.0. I can clone 63.0.0 successfully. It looks like the `--vers` string is being treated as `^64.0.0` not `=64.0.0`.

I tried using `=64.0.0` and `<=64.0.0` but got the error `error: cannot parse '=64.0.0' as a semver`.

**Comment by iwillspeak** [comment]
Any update on this?

**Comment by pravic** [comment]
It is even worse: 

`cargo clone tokei --vers 6.1.3` clones 6.1.3
`cargo clone tokei --vers 6.1.2` clones 6.1.3 as well
`cargo clone tokei --vers =6.1.3` throws an error with `cannot parse '=6.1.3' as a semver`.

**Comment by pravic** [comment]
@JanLikar is it possible to clone a specific version? May be I am missing something?

**Comment by JanLikar** [comment]
The version argument gets passed to cargo and is not altered by cargo-clone in any way. I guess this is the default behaviour... The only thing I can say at this time is, I will have to check what builtin commands do with the version specification and mimic that, because mirroring Cargo builtins is one of the goals of this crate.

**Comment by smvoss** [comment]
https://github.com/rust-lang/cargo/pull/4229 may include the answer to this issue.

It looks as if wrapping the passed down arguments explicitly in quotation marks will make sure it gets parsed correctly, and the ranges will be respected.

**Comment by jethrogb** [comment]
Just use whatever the equivalent of `--precise` is

**Comment by repi** [comment]
this is still broken

**Comment by JanLikar** [comment]
I'll see what I can do, I have some time for this now.
