### ISSUE TITLE
Command line args not working on Windows

### ISSUE THREAD

**Issue by hlavaatch** [JanLikar/cargo-clone#20]
Command line argument parsing does not seem to work on Windows,
i get just
```
C:\rust>cargo clone -h
Invalid arguments.

Usage:
    cargo clone [options] [<crate>]
```
whatever I pass to it.
Is unusable 👎

**Comment by repi** [comment]
Works for me on latest on Windows

**Comment by JanLikar** [comment]
Can't reproduce.

**Comment by hlavaatch** [comment]
seems to be working now, ok to close

**Comment by JanLikar** [comment]
I'm glad to hear that!
