### ISSUE TITLE
Cargo clone cannot parse `Cargo.toml` manifest for some crates

### ISSUE THREAD

**Issue by Phosphorus15** [JanLikar/cargo-clone#26]
It is discovered that `cargo clone` cannot properly handle some `Cargo.toml` file and would panic even if it is correct, example is shown below
```shell
$ cargo clone rand
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to parse manifest at `C:\Users\Phosphorus15\.cargo\registry\src\github.com-1ecc6299db9ec823\rand-0.7.1\Cargo.toml`
```
I've discovered that this problem is because the `cargo` crate (version `0.30.0`) is outdated, and I switch it to version `0.38.0` (the latest version), it seems to fix the problem after some tweaking (some of the methods signature have changed).

A pr will be created soon to fully fix this problem.

**Comment by Phosphorus15** [comment]
I suggest dumping a new version for this pr, because it really matters to the functionality of this subcommand.

Many crates was previously unable to be cloned because of this.

**Comment by repi** [comment]
Thanks for reporting, rarn into multiple crates myself that had this problem
