### ISSUE TITLE
Add a way to specify output dir

### ISSUE THREAD

**Issue by JanLikar** [JanLikar/cargo-clone#3]

**Comment by pravic** [comment]
Unfortunately this option (`--prefix`) does not create specified directory.

**Comment by JanLikar** [comment]
This would be a great improvement.

Can you think of a case where this behaviour would be unwanted? If there are no such cases, I don't see a problem in adding this.

**Comment by pravic** [comment]
For example, `git clone` creates a new directory (if it not exists) and fails only if the provided directory exists and is not empty. 

I think, it is better to follow the least surprise way in the cargo-clone as well.

**Comment by JanLikar** [comment]
Sure, sounds reasonable. Would you like to implement this? If not, I will do it as soon as time allows.
