### ISSUE TITLE
Remove option to clone from git repo

### ISSUE THREAD

**Issue by JanLikar** [JanLikar/cargo-clone#37]
On second thought, having this is completely useless.

Why would I want to do

    cargo clone --git https://github.com/JanLikar/cargo-clone.git
    
Instead of

    git clone https://github.com/JanLikar/cargo-clone.git

I'm planning to remove this functionality to simplify the command, unless someone has good arguments against it.

**Comment by repi** [comment]
Does indeed not sound that useful to have :)
