### ISSUE TITLE
v1.0.1 tag has changed

### ISSUE THREAD

**Issue by Xiretza** [JanLikar/cargo-clone#48]
Hi! It looks like the [v1.0.1 tag](https://github.com/JanLikar/cargo-clone/releases/tag/v1.0.1) was created two days ago pointing to 3cc5bddb458fb82d502d806a113611b085ed92cd, but since that commit contained an error (Cargo.lock wasn't updated), it was changed to point to d176523c969ca687e6e20a5e289f9a48ce940192 instead. Please don't do that - release tags are meant to be immutable references, and changing them to suddenly point to a different commit causes all kinds of issues with software that expects that not to happen (in my case, `makepkg` when building the [AUR package](https://aur.archlinux.org/packages/cargo-clone)). If a release contains a small bug, simply create another patch release (v1.0.2 in this case) that fixes the issue, people will update to that instead. Thanks!

**Comment by JanLikar** [comment]
Hi, I'm sorry about that, that was an oversight. Would releasing v1.0.2 now make things any better for you?

**Comment by JanLikar** [comment]
Thank you for pointing it out, I assumed nobody cared about this repo's tags. I will be more careful in the future.
