### ISSUE TITLE
Only works for crates with a repo?

### ISSUE THREAD

**Issue by melMass** [JanLikar/cargo-clone#53]
Hi,

I'm coming from cargo-download that is unmaintained but allowed repository less crates to be downloaded, this doesn't seem possible with cargo-clone or I'm missing something?

Thanks

**Comment by JanLikar** [comment]
cargo-clone pulls from the index directly by default. Only `cargo clone --git` requires a repository.

If you're having trouble with a specific crate, let me know so I can take a look.

**Comment by melMass** [comment]
> If you're having trouble with a specific crate, let me know so I can take a look.

Thanks I wanted to be sure.
Yes for instance egui_nodes

**Comment by dtolnay** [comment]
Seems to work in my case.

```console
$ cargo clone egui_nodes
    Updating crates.io index
note: Downloading egui_nodes 0.1.3
  Downloaded egui_nodes v0.1.3
  Downloaded 1 crate (4.9 MB) in 0.90s

$ ls egui_nodes/
Cargo.lock  Cargo.toml  Cargo.toml.orig  examples  LICENSE  media  README.md  rustfmt.toml  src
```

**Comment by melMass** [comment]
My bad, but I guess interesting find! 
cargo download actually tries alternative underscore/hypens. 
So 

```zsh
# This is actually replace by egui_nodes
cargo download egui-nodes
```
does work.
Not sure if `clone` is interested in this behaviour

**Comment by JanLikar** [comment]
I'm not sure this is something I want for cargo clone. I get suspicious when encountering this kind of magic behavior.

**Comment by melMass** [comment]
> I'm not sure this is something I want for cargo clone. I get suspicious when encountering this kind of magic behavior.

Agreed but I would vote for a suggestion fallback: egui-nodes not found, did you meant egui_nodes?

**Comment by JanLikar** [comment]
> Agreed but I would vote for a suggestion fallback: egui-nodes not found, did you meant egui_nodes?
Good idea, we could do this. Can you open a ticket for it?
