### ISSUE TITLE
Cannot install on Windows

### ISSUE THREAD

**Issue by pravic** [JanLikar/cargo-clone#8]
> error: failed to compile `cargo-clone v0.1.0`
> Caused by:
>   build script output was not valid utf-8

When building from repo:

> Couldn't find libcurl from pkgconfig ("pkg-config doesn\'t handle cross compilation. Use PKG_CONFIG_ALLOW_CROSS=1 to override"), compiling it from source...
> ...
> curl-sys-0.1.30\curl\lib\curl_setup.h(132): fatal error C1083: Cannot open include file: 'curl/curlbuild.h': No such file or directory

It seems, curl-sys wont to be compiled.

**Comment by JanLikar** [comment]
This error, like you have correctly noted, suggests that curl-sys couldn't be compiled successfully. This isn't really a problem of cargo-clone per se - cargo-clone depends on Cargo and one of Cargo's dependencies is curl. I'm currently unable to reproduce this bug, as I don't have a Windows computer anywhere near me. 

If you can, please provide more information; Windows, Cargo and Rust versions would be useful, additionally it would be beneficial to know whether you have GNU or MSVC ABI Rust compiler installed.

I am not really sure, but you might be able to fix this by manually installing lib-curl.

**Comment by JanLikar** [comment]
I have published a new version of this crate that features the latest stable version of Cargo. Could you try installing cargo-clone again, to see if the problem persists?

**Comment by pravic** [comment]
Well, despite of cmake requirement, it compiles well. curl-sys was fixed times ago for windows.

**Comment by JanLikar** [comment]
Thank you, if you spot any other issues, you're more than welcome to report them.

**Comment by DTibbs** [comment]
Just wanted to add, you must use the `<arch>-pc-windows-msvc` rust toolchain to successfully compile/install cargo-clone. I was getting cryptic compile errors from the various dependencies using `<arch>-pc-windows-gnu` on latest. (v0.1.2 at time of writing)
