### ISSUE TITLE
Can't install using cargo install

### ISSUE THREAD

**Issue by jethrogb** [JanLikar/cargo-clone#9]
Since openssl-sys 0.9.0 has been released, cargo's dependency resolution mechanism is unable to automatically choose a single openssl-sys version for this crate, resulting in a failed build:
```
  native library `openssl` is being linked to by more than one version of the same package, but it can only be linked once; try updating or pinning your dependencies to ensure that this package only shows up once
```

When I clone manually and do:
```
cargo update -p openssl-sys:0.9.0 --precise 0.7.17
```
everything builds fine.

**Comment by JanLikar** [comment]
I have published a new version of this crate that features the latest stable version of Cargo. Could you try installing cargo-clone again, to see if the problem persists?

**Comment by smvoss** [comment]
```rust
Programming ❯ cargo install cargo-clone --root rust/dl
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing cargo-clone v0.1.2
   Compiling regex-syntax v0.4.2

  [snip]

   Compiling cargo-clone v0.1.2
    Finished release [optimized] target(s) in 234.45 secs
  Installing rust/dl/bin/cargo-clone
warning: be sure to add `rust/dl/bin` to your PATH to be able to run the installed binaries
```

+1

**Comment by jethrogb** [comment]
I think I installed it recently and it worked fine. But there was another problem that led me to use [cargo-clone-crate](https://crates.io/crates/cargo-clone-crate) instead.
